brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0

brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

deleteWhen=04
fileReservedTime=48

listenPort=10911

namesrvAddr=namesrv:9876

autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true

brokerIP1=192.168.253.1