INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000000, NULL, NOW(), 0, NULL, NOW(), '', NULL, '', '', '', 'ReadOutlined', NULL, 2000, 1, '内容管理', 0, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000001, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:info:page', 'views/content/info/index', '', 'FileTextOutlined', 399000000000000000, 1000, 1, '内容', 1, '/content/info');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000002, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:info:add', '', '', '', 399000000000000001, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000003, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:info:delete', '', '', '', 399000000000000001, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000004, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:info:update', '', '', '', 399000000000000001, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000011, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:body:page', 'views/content/body/index', '', 'FileMarkdownOutlined', 399000000000000000, 1010, 1, '正文', 1, '/content/body');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000012, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:body:add', '', '', '', 399000000000000011, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000013, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:body:delete', '', '', '', 399000000000000011, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000014, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:body:update', '', '', '', 399000000000000011, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000021, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:comment:page', 'views/content/comment/index', '', 'CommentOutlined', 399000000000000000, 1020, 1, '评论', 1, '/content/comment');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000022, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:comment:add', '', '', '', 399000000000000021, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000023, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:comment:delete', '', '', '', 399000000000000021, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000024, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:comment:update', '', '', '', 399000000000000021, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000031, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:category:page', 'views/content/category/index', '', 'PartitionOutlined', 399000000000000000, 1030, 1, '分类', 1, '/content/category');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000032, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:category:add', '', '', '', 399000000000000031, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000033, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:category:delete', '', '', '', 399000000000000031, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000034, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:category:update', '', '', '', 399000000000000031, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000041, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:categoryRel:page', 'views/content/categoryRel/index', '', 'LinkOutlined', 399000000000000000, 1040, 1, '分类关联', 1, '/content/categoryRel');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000042, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:categoryRel:add', '', '', '', 399000000000000041, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000043, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:categoryRel:delete', '', '', '', 399000000000000041, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000044, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:categoryRel:update', '', '', '', 399000000000000041, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000051, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:tag:page', 'views/content/tag/index', '', 'TagOutlined', 399000000000000000, 1050, 1, '标签', 1, '/content/tag');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000052, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:tag:add', '', '', '', 399000000000000051, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000053, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:tag:delete', '', '', '', 399000000000000051, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000054, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:tag:update', '', '', '', 399000000000000051, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000061, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:tagRel:page', 'views/content/tagRel/index', '', 'LinkOutlined', 399000000000000000, 1060, 1, '标签关联', 1, '/content/tagRel');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000062, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:tagRel:add', '', '', '', 399000000000000061, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000063, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:tagRel:delete', '', '', '', 399000000000000061, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000064, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:tagRel:update', '', '', '', 399000000000000061, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000071, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:attachment:page', 'views/content/attachment/index', '', 'PaperClipOutlined', 399000000000000000, 1070, 1, '附件', 1, '/content/attachment');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000072, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:attachment:add', '', '', '', 399000000000000071, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000073, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:attachment:delete', '', '', '', 399000000000000071, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000074, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:attachment:update', '', '', '', 399000000000000071, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000081, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:like:page', 'views/content/like/index', '', 'LikeOutlined', 399000000000000000, 1080, 1, '点赞记录', 1, '/content/like');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000082, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:like:add', '', '', '', 399000000000000081, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000083, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:like:delete', '', '', '', 399000000000000081, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000084, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:like:update', '', '', '', 399000000000000081, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000091, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:favorite:page', 'views/content/favorite/index', '', 'StarOutlined', 399000000000000000, 1090, 1, '收藏记录', 1, '/content/favorite');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000092, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:favorite:add', '', '', '', 399000000000000091, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000093, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:favorite:delete', '', '', '', 399000000000000091, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000094, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:favorite:update', '', '', '', 399000000000000091, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000101, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:viewLog:page', 'views/content/viewLog/index', '', 'EyeOutlined', 399000000000000000, 1100, 1, '浏览记录', 1, '/content/viewLog');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000102, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:viewLog:add', '', '', '', 399000000000000101, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000103, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:viewLog:delete', '', '', '', 399000000000000101, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000104, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:viewLog:update', '', '', '', 399000000000000101, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000111, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:auditLog:page', 'views/content/auditLog/index', '', 'SafetyOutlined', 399000000000000000, 1110, 1, '审核记录', 1, '/content/auditLog');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000112, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:auditLog:add', '', '', '', 399000000000000111, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000113, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:auditLog:delete', '', '', '', 399000000000000111, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000114, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:auditLog:update', '', '', '', 399000000000000111, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000121, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:revision:page', 'views/content/revision/index', '', 'HistoryOutlined', 399000000000000000, 1120, 1, '修订记录', 1, '/content/revision');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000122, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:revision:add', '', '', '', 399000000000000121, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000123, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:revision:delete', '', '', '', 399000000000000121, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000124, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:revision:update', '', '', '', 399000000000000121, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000131, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:commentLike:page', 'views/content/commentLike/index', '', 'LikeOutlined', 399000000000000000, 1130, 1, '评论点赞', 1, '/content/commentLike');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000132, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:commentLike:add', '', '', '', 399000000000000131, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000133, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:commentLike:delete', '', '', '', 399000000000000131, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000134, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:commentLike:update', '', '', '', 399000000000000131, 0, 1, '修改', 2, '');

INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000141, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:report:page', 'views/content/report/index', '', 'WarningOutlined', 399000000000000000, 1140, 1, '举报', 1, '/content/report');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000142, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:report:add', '', '', '', 399000000000000141, 0, 1, '添加', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000143, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:report:delete', '', '', '', 399000000000000141, 0, 1, '删除', 2, '');
INSERT INTO "public"."sys_permissions" ("id", "create_by", "create_time", "deleted", "update_by", "update_time", "application_code", "application_id", "code", "component", "component_name", "icon", "parent_id", "sort", "status", "title", "type", "url") VALUES (399000000000000144, NULL, NOW(), 0, NULL, NOW(), '', NULL, 'admin:content:report:update', '', '', '', 399000000000000141, 0, 1, '修改', 2, '');

